//
//  Neuromobile.h
//  CommonSDK
//
//  Created by Marc Estrada on 4/7/17.
//  Copyright © 2017 Neuromobile. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "NeuromobileUser.h"
#import "NeuromobileService.h"
#import "NeuromobileDelegate.h"
#import "NMCSpcModule.h"

/*!
 @brief Controls the SCP (Single Configuration Point) operations such as initializing the SCP, services and user session.
 @version 1.0
 */
@interface Neuromobile : NSObject

/*!
 @brief Initializes SCP for the given license secret.
 If the secret is nil an NSException will be thrown.
 @param secret Client secret
 @version 1.0
 */
+(void) initWithSecret:(NSString *)secret;


+(void)downloadSpcModuleWithSuccess:(void(^)(NMCSpcModule *))successCallback onError:(void(^)())errorCallback;

/*!
 @brief Initializes a session for the provided NeuromobileUser model.
 Before providing a NeuromobileUser, the CommonSDK must be initialized by calling Neuromobile::initWithSecret:.
 @param user A NeuromobileUser model which is used in statistics system.
 @param listener A NeuromobileDelegate implementation to receive callbacks form Neuromobile handler.
 @version 1.0
 */
+(void) setUser:(NeuromobileUser *)user withDelegate:(NSObject<NeuromobileDelegate> *)listener;
/*!
 @brief Initializes a session for the provided NeuromobileUser model.
 You can specify whether this user is anonymous (they have an autogenerated email) or not. Setting an user as anonymous will make the statistics system ignore its data as it cannot be classified.
 Before providing a NeuromobileUser, the CommonSDK must be initialized by calling Neuromobile::initWithSecret:.
 @param user A NeuromobileUser model which is used in statistics system.
 @param delegate A NeuromobileDelefate implementation to receive callbacks form Neuromobile handler.
 @version 1.0
 */
+(void) setUser:(NeuromobileUser *)user anonymous:(BOOL)anonymousUser withDelegate:(NSObject<NeuromobileDelegate> *)delegate;
+(void) setToken:(NSString *)token email:(NSString *)email withDelegate:(NSObject<NeuromobileDelegate> *)listener;
/*!
 @brief Checks whether a service can be initialized.
 Before any substantiation, a NeuromobileUser must be set by using Neuromobile::setUser:withListener: method.
 @param service A NeuromobileService model which represents a service provided by SCP.
 @version 1.0
 */
+(void) initService:(NSObject<NeuromobileService> *)service;
/*!
 @brief Method to change user password.
 @param newPassword New password
 @param successCallback A block called if the password was succesfully changed.
 @param errorCallback A block called if there was an error changing the password.
 @version 1.0
 */
+(void) changeUserPassword:(NSString *)newPassword successBlock:(void(^)())successCallback errorBlock:(void(^)(NSString *error))errorCallback;
/*!
 @brief Closes the NeuromobileUser session and stops all initialized services.
 @version 1.0
 */
+(void) closeUserSession;

+(NSString *) getSdkVersion;

+ (void)performBackgroundFetch;

+ (void)moduleBackgroundFetch:(NSObject<NeuromobileService> *)service;

+ (NSString *) getDeviceModel;

@end
